[project]
name = "landlock-website"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "myst-parser>=4.0",
    "sphinx>=8.2",
    "sphinx-book-theme>=1.1",
    "sphinx-design>=0.6",
]

[tool.uv]
package = false
